import 'api_models.dart';

class DemoSeed {
  static final me = UserProfile(
    id: 'usr_demo',
    email: 'demo@surftravel.app',
    displayName: 'Maya Surfer',
    homeRegion: 'Bali',
    locale: 'en',
    premium: false,
    freeLiveSpotId: 'spot_uluwatu_peak',
    adsEnabled: true,
    favoriteSpotIds: const ['spot_balangan', 'spot_echo_beach'],
  );

  static final spots = [
    SpotModel(
      id: 'spot_uluwatu_peak',
      name: 'Uluwatu Peak',
      country: 'Indonesia',
      region: 'Bali',
      area: 'Uluwatu',
      latitude: -8.8184,
      longitude: 115.0889,
      difficulty: 'advanced',
      bestMonths: const ['Apr', 'May', 'Jun', 'Jul', 'Aug'],
      waveHeightM: 1.9,
      waterTempC: 27,
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
      summary: 'Powerful reef break with sunrise energy and serious walls.',
    ),
    SpotModel(
      id: 'spot_padang_padang',
      name: 'Padang Padang',
      country: 'Indonesia',
      region: 'Bali',
      area: 'Uluwatu',
      latitude: -8.8057,
      longitude: 115.1018,
      difficulty: 'advanced',
      bestMonths: const ['Apr', 'May', 'Jun', 'Jul', 'Aug'],
      waveHeightM: 1.6,
      waterTempC: 27,
      imageUrl: 'https://images.unsplash.com/photo-1473116763249-2faaef81ccda',
      summary:
          'Barreling reef setup with a compact takeoff and classic dry-season energy.',
    ),
    SpotModel(
      id: 'spot_balangan',
      name: 'Balangan',
      country: 'Indonesia',
      region: 'Bali',
      area: 'Uluwatu',
      latitude: -8.7907,
      longitude: 115.1212,
      difficulty: 'intermediate',
      bestMonths: const ['Apr', 'May', 'Jun', 'Jul', 'Aug'],
      waveHeightM: 1.5,
      waterTempC: 27,
      imageUrl: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21',
      summary:
          'Long playful left with easier paddling than the heaviest Bukit reefs.',
    ),
    SpotModel(
      id: 'spot_echo_beach',
      name: 'Echo Beach',
      country: 'Indonesia',
      region: 'Bali',
      area: 'Canggu',
      latitude: -8.6481,
      longitude: 115.1385,
      difficulty: 'intermediate',
      bestMonths: const ['Apr', 'May', 'Jun', 'Sep'],
      waveHeightM: 1.4,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21',
      summary: 'Flexible beach and reef options with easy trip logistics.',
    ),
    SpotModel(
      id: 'spot_batu_bolong',
      name: 'Batu Bolong',
      country: 'Indonesia',
      region: 'Bali',
      area: 'Canggu',
      latitude: -8.6618,
      longitude: 115.1303,
      difficulty: 'beginner',
      bestMonths: const ['Apr', 'May', 'Jun', 'Sep'],
      waveHeightM: 1.0,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1493558103817-58b2924bce98',
      summary:
          'Friendly longboard wave with mellow takeoffs and easy post-surf hangs.',
    ),
    SpotModel(
      id: 'spot_berawa',
      name: 'Berawa',
      country: 'Indonesia',
      region: 'Bali',
      area: 'Canggu',
      latitude: -8.6591,
      longitude: 115.1344,
      difficulty: 'intermediate',
      bestMonths: const ['Apr', 'May', 'Jun', 'Sep'],
      waveHeightM: 1.3,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
      summary:
          'Punchier beach break peaks with plenty of movement through the tides.',
    ),
    SpotModel(
      id: 'spot_siargao',
      name: 'Cloud 9',
      country: 'Philippines',
      region: 'Siargao',
      area: 'General Luna',
      latitude: 9.8136,
      longitude: 126.1661,
      difficulty: 'advanced',
      bestMonths: const ['Sep', 'Oct', 'Nov'],
      waveHeightM: 1.7,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
      summary:
          'Fast reef setup with punchy walls and a world-class surf trip vibe.',
    ),
    SpotModel(
      id: 'spot_jacking_horse',
      name: 'Jacking Horse',
      country: 'Philippines',
      region: 'Siargao',
      area: 'General Luna',
      latitude: 9.8084,
      longitude: 126.1654,
      difficulty: 'intermediate',
      bestMonths: const ['Sep', 'Oct', 'Nov'],
      waveHeightM: 1.2,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
      summary:
          'More approachable Siargao reef option with playful walls on medium swells.',
    ),
    SpotModel(
      id: 'spot_quicksilver',
      name: 'Quicksilver',
      country: 'Philippines',
      region: 'Siargao',
      area: 'General Luna',
      latitude: 9.8008,
      longitude: 126.1587,
      difficulty: 'advanced',
      bestMonths: const ['Sep', 'Oct', 'Nov'],
      waveHeightM: 1.5,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1519046904884-53103b34b206',
      summary:
          'Fast playful right that lights up on cleaner swells just down the road from Cloud 9.',
    ),
    SpotModel(
      id: 'spot_pacifico',
      name: 'Pacifico',
      country: 'Philippines',
      region: 'Siargao',
      area: 'Pacifico',
      latitude: 9.9875,
      longitude: 126.0864,
      difficulty: 'intermediate',
      bestMonths: const ['Oct', 'Nov', 'Dec'],
      waveHeightM: 1.4,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
      summary:
          'Scenic reef and beach setup on Siargao’s quieter north side with more room to move.',
    ),
    SpotModel(
      id: 'spot_monaliza',
      name: 'Monaliza',
      country: 'Philippines',
      region: 'Siargao',
      area: 'Pilar',
      latitude: 9.8628,
      longitude: 126.1101,
      difficulty: 'intermediate',
      bestMonths: const ['Oct', 'Nov', 'Dec'],
      waveHeightM: 1.3,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21',
      summary:
          'Long left with playful sections that makes a strong alternative when Cloud 9 is crowded.',
    ),
    SpotModel(
      id: 'spot_urmizno',
      name: 'Urmizno',
      country: 'Philippines',
      region: 'La Union',
      area: 'San Juan',
      latitude: 16.6767,
      longitude: 120.3312,
      difficulty: 'intermediate',
      bestMonths: const ['Oct', 'Nov', 'Dec', 'Jan'],
      waveHeightM: 1.2,
      waterTempC: 27,
      imageUrl: 'https://images.unsplash.com/photo-1493558103817-58b2924bce98',
      summary:
          'The heart of the La Union scene with rippable peaks, surf schools, and easy access.',
    ),
    SpotModel(
      id: 'spot_monaliza_baler',
      name: 'Sabang Beach',
      country: 'Philippines',
      region: 'Baler',
      area: 'Sabang',
      latitude: 15.7606,
      longitude: 121.5605,
      difficulty: 'beginner',
      bestMonths: const ['Oct', 'Nov', 'Dec', 'Jan'],
      waveHeightM: 1.1,
      waterTempC: 27,
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
      summary:
          'Beginner-friendly beach break with lots of local history and easy day-long sessions.',
    ),
    SpotModel(
      id: 'spot_crystal_beach',
      name: 'Crystal Beach',
      country: 'Philippines',
      region: 'Zambales',
      area: 'San Narciso',
      latitude: 15.0369,
      longitude: 120.0806,
      difficulty: 'beginner',
      bestMonths: const ['Oct', 'Nov', 'Dec', 'Jan'],
      waveHeightM: 1.0,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
      summary:
          'Easy-access beach break weekend zone for Manila surfers and newer riders.',
    ),
    SpotModel(
      id: 'spot_stimpy',
      name: "Stimpy's",
      country: 'Indonesia',
      region: 'Mentawai',
      area: 'Playgrounds',
      latitude: -2.1683,
      longitude: 99.7836,
      difficulty: 'advanced',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug', 'Sep'],
      waveHeightM: 1.8,
      waterTempC: 29,
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
      summary:
          'Mechanical left reef in the Mentawais with boat-trip dream energy.',
    ),
    SpotModel(
      id: 'spot_lances_right',
      name: "Lance's Right",
      country: 'Indonesia',
      region: 'Mentawai',
      area: 'Playgrounds',
      latitude: -2.2974,
      longitude: 99.9729,
      difficulty: 'advanced',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug', 'Sep'],
      waveHeightM: 1.9,
      waterTempC: 29,
      imageUrl: 'https://images.unsplash.com/photo-1519046904884-53103b34b206',
      summary:
          'Long wrapping right with one of the most photogenic walls in Indonesia.',
    ),
    SpotModel(
      id: 'spot_desert_point',
      name: 'Desert Point',
      country: 'Indonesia',
      region: 'Lombok',
      area: 'Sekotong',
      latitude: -8.7498,
      longitude: 115.9255,
      difficulty: 'advanced',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug'],
      waveHeightM: 2.0,
      waterTempC: 27,
      imageUrl: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21',
      summary:
          'Legendary freight-train left that turns on when the swell and wind line up.',
    ),
    SpotModel(
      id: 'spot_lakey_peak',
      name: 'Lakey Peak',
      country: 'Indonesia',
      region: 'Sumbawa',
      area: "Hu'u",
      latitude: -8.4893,
      longitude: 118.9973,
      difficulty: 'intermediate',
      bestMonths: const ['Apr', 'May', 'Jun', 'Jul', 'Aug'],
      waveHeightM: 1.6,
      waterTempC: 27,
      imageUrl: 'https://images.unsplash.com/photo-1493558103817-58b2924bce98',
      summary:
          'Rippable peak with rights and lefts, perfect for a strike mission in Sumbawa.',
    ),
    SpotModel(
      id: 'spot_nias',
      name: 'Lagundri Bay',
      country: 'Indonesia',
      region: 'Nias',
      area: 'Sorake',
      latitude: 0.5715,
      longitude: 97.8342,
      difficulty: 'advanced',
      bestMonths: const ['Jun', 'Jul', 'Aug', 'Sep'],
      waveHeightM: 1.9,
      waterTempC: 29,
      imageUrl: 'https://images.unsplash.com/photo-1473116763249-2faaef81ccda',
      summary:
          'Machine-like right-hander with a deep surf heritage and serious power.',
    ),
    SpotModel(
      id: 'spot_da_nang',
      name: 'My Khe Beach',
      country: 'Vietnam',
      region: 'Da Nang',
      area: 'Da Nang',
      latitude: 16.0741,
      longitude: 108.2468,
      difficulty: 'beginner',
      bestMonths: const ['Sep', 'Oct', 'Nov', 'Dec'],
      waveHeightM: 1.1,
      waterTempC: 26,
      imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
      summary:
          'Accessible city beach with a growing local scene and easy first sessions.',
    ),
    SpotModel(
      id: 'spot_non_nuoc',
      name: 'Non Nuoc Beach',
      country: 'Vietnam',
      region: 'Da Nang',
      area: 'Ngu Hanh Son',
      latitude: 15.9976,
      longitude: 108.2669,
      difficulty: 'beginner',
      bestMonths: const ['Sep', 'Oct', 'Nov', 'Dec'],
      waveHeightM: 1.0,
      waterTempC: 26,
      imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
      summary:
          'More relaxed southern Da Nang beach stretch with roomier peaks and mellow travel flow.',
    ),
    SpotModel(
      id: 'spot_mui_ne',
      name: 'Suoi Nuoc',
      country: 'Vietnam',
      region: 'Mui Ne',
      area: 'Mui Ne',
      latitude: 10.9827,
      longitude: 108.3284,
      difficulty: 'intermediate',
      bestMonths: const ['Nov', 'Dec', 'Jan', 'Feb'],
      waveHeightM: 1.2,
      waterTempC: 27,
      imageUrl: 'https://images.unsplash.com/photo-1473116763249-2faaef81ccda',
      summary:
          'Windy open-ocean stretch with more size than central-town beaches during the season.',
    ),
    SpotModel(
      id: 'spot_nha_trang',
      name: 'Bai Dai',
      country: 'Vietnam',
      region: 'Nha Trang',
      area: 'Cam Lam',
      latitude: 12.0624,
      longitude: 109.1959,
      difficulty: 'beginner',
      bestMonths: const ['Oct', 'Nov', 'Dec'],
      waveHeightM: 1.0,
      waterTempC: 27,
      imageUrl: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21',
      summary:
          'Long sandy stretch south of Nha Trang with easy beach-break entries and space to spread out.',
    ),
    SpotModel(
      id: 'spot_vung_tau',
      name: 'Back Beach',
      country: 'Vietnam',
      region: 'Vung Tau',
      area: 'Vung Tau',
      latitude: 10.3354,
      longitude: 107.0907,
      difficulty: 'beginner',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug', 'Sep'],
      waveHeightM: 0.9,
      waterTempC: 29,
      imageUrl: 'https://images.unsplash.com/photo-1493558103817-58b2924bce98',
      summary:
          'Popular city beach with smaller summer surf and easy access from Ho Chi Minh City.',
    ),
    SpotModel(
      id: 'spot_kata',
      name: 'Kata Beach',
      country: 'Thailand',
      region: 'Phuket',
      area: 'Kata',
      latitude: 7.8215,
      longitude: 98.2972,
      difficulty: 'beginner',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug', 'Sep'],
      waveHeightM: 1.0,
      waterTempC: 29,
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
      summary:
          'Fun monsoon-season beach break with mellow travel logistics and warm water.',
    ),
    SpotModel(
      id: 'spot_kalim',
      name: 'Kalim Beach',
      country: 'Thailand',
      region: 'Phuket',
      area: 'Patong',
      latitude: 7.9135,
      longitude: 98.2852,
      difficulty: 'intermediate',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug', 'Sep'],
      waveHeightM: 1.1,
      waterTempC: 29,
      imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
      summary:
          'Rocky reef-and-beach mix with punchier sections than the friendlier Phuket learner waves.',
    ),
    SpotModel(
      id: 'spot_nai_harn',
      name: 'Nai Harn',
      country: 'Thailand',
      region: 'Phuket',
      area: 'Rawai',
      latitude: 7.7802,
      longitude: 98.3047,
      difficulty: 'beginner',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug', 'Sep'],
      waveHeightM: 0.9,
      waterTempC: 29,
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
      summary:
          'Friendly shoulder-season Phuket option with smaller surf and an easy beach vibe.',
    ),
    SpotModel(
      id: 'spot_memories',
      name: 'Memories Beach',
      country: 'Thailand',
      region: 'Khao Lak',
      area: 'Takua Pa',
      latitude: 8.8778,
      longitude: 98.2148,
      difficulty: 'beginner',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug', 'Sep'],
      waveHeightM: 1.0,
      waterTempC: 29,
      imageUrl: 'https://images.unsplash.com/photo-1519046904884-53103b34b206',
      summary:
          'One of Thailand’s most welcoming surf beaches with mellow peaks and a strong beginner scene.',
    ),
    SpotModel(
      id: 'spot_koh_phayam',
      name: 'Aow Yai',
      country: 'Thailand',
      region: 'Koh Phayam',
      area: 'Ranong',
      latitude: 9.7304,
      longitude: 98.4102,
      difficulty: 'intermediate',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug', 'Sep'],
      waveHeightM: 1.2,
      waterTempC: 29,
      imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
      summary:
          'Remote Andaman island setup with fun seasonal surf and a low-key travel feel.',
    ),
    SpotModel(
      id: 'spot_cherating',
      name: 'Cherating',
      country: 'Malaysia',
      region: 'Pahang',
      area: 'Cherating',
      latitude: 4.1232,
      longitude: 103.3891,
      difficulty: 'beginner',
      bestMonths: const ['Nov', 'Dec', 'Jan', 'Feb'],
      waveHeightM: 1.1,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1493558103817-58b2924bce98',
      summary:
          'Malaysia’s best-known surf zone with easy beach-break learning conditions during the monsoon.',
    ),
    SpotModel(
      id: 'spot_batu_burok',
      name: 'Batu Burok',
      country: 'Malaysia',
      region: 'Terengganu',
      area: 'Kuala Terengganu',
      latitude: 5.3078,
      longitude: 103.1548,
      difficulty: 'beginner',
      bestMonths: const ['Nov', 'Dec', 'Jan'],
      waveHeightM: 1.0,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
      summary:
          'Fun northeast monsoon beach break that helps round out Peninsular Malaysia surf trips.',
    ),
    SpotModel(
      id: 'spot_kudat',
      name: 'Kudat Left',
      country: 'Malaysia',
      region: 'Sabah',
      area: 'Kudat',
      latitude: 6.8944,
      longitude: 116.8354,
      difficulty: 'intermediate',
      bestMonths: const ['Dec', 'Jan', 'Feb'],
      waveHeightM: 1.3,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
      summary:
          'Remote Borneo corner with more adventurous surf-travel appeal and less crowded lineups.',
    ),
    SpotModel(
      id: 'spot_ngwe_saung',
      name: 'Ngwe Saung Beach',
      country: 'Myanmar',
      region: 'Ayeyarwady',
      area: 'Ngwe Saung',
      latitude: 16.9642,
      longitude: 94.4362,
      difficulty: 'beginner',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug', 'Sep'],
      waveHeightM: 1.0,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21',
      summary:
          'Undeveloped beach-break zone with frontier travel energy and soft seasonal surf.',
    ),
    SpotModel(
      id: 'spot_nabule',
      name: 'Nabule Beach',
      country: 'Myanmar',
      region: 'Tanintharyi',
      area: 'Dawei',
      latitude: 14.0955,
      longitude: 98.1956,
      difficulty: 'intermediate',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug'],
      waveHeightM: 1.2,
      waterTempC: 29,
      imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
      summary:
          'Remote southern Myanmar coastline with more open-ocean exposure than the country’s better-known beaches.',
    ),
    SpotModel(
      id: 'spot_areia_branca',
      name: 'Areia Branca',
      country: 'Timor-Leste',
      region: 'Dili',
      area: 'Dili',
      latitude: -8.5447,
      longitude: 125.5597,
      difficulty: 'beginner',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug', 'Sep'],
      waveHeightM: 0.9,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
      summary:
          'Capital-adjacent beach option that helps introduce Timor-Leste into the surf-travel map.',
    ),
    SpotModel(
      id: 'spot_jaco',
      name: 'Jaco Island',
      country: 'Timor-Leste',
      region: 'Lautem',
      area: 'Tutuala',
      latitude: -8.4205,
      longitude: 127.3254,
      difficulty: 'intermediate',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug', 'Sep'],
      waveHeightM: 1.3,
      waterTempC: 28,
      imageUrl: 'https://images.unsplash.com/photo-1519046904884-53103b34b206',
      summary:
          'Far-east Timor adventure zone with empty-lineup fantasy energy and serious travel-story value.',
    ),
    SpotModel(
      id: 'spot_scarborough',
      name: 'Scarborough Beach',
      country: 'Australia',
      region: 'Western Australia',
      area: 'Perth',
      latitude: -31.8945,
      longitude: 115.7512,
      difficulty: 'beginner',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug'],
      waveHeightM: 1.1,
      waterTempC: 21,
      imageUrl: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21',
      summary:
          'Perth city beach with accessible peaks and a great local content-and-lifestyle angle.',
    ),
    SpotModel(
      id: 'spot_trigg',
      name: 'Trigg Point',
      country: 'Australia',
      region: 'Western Australia',
      area: 'Perth',
      latitude: -31.8725,
      longitude: 115.7573,
      difficulty: 'intermediate',
      bestMonths: const ['May', 'Jun', 'Jul', 'Aug'],
      waveHeightM: 1.4,
      waterTempC: 21,
      imageUrl: 'https://images.unsplash.com/photo-1493558103817-58b2924bce98',
      summary:
          'Perth’s most recognizable surf zone with more punch and a strong local crowd when it is on.',
    ),
    SpotModel(
      id: 'spot_yallingup',
      name: 'Yallingup',
      country: 'Australia',
      region: 'Western Australia',
      area: 'Margaret River',
      latitude: -33.6466,
      longitude: 115.0187,
      difficulty: 'intermediate',
      bestMonths: const ['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
      waveHeightM: 1.8,
      waterTempC: 20,
      imageUrl: 'https://images.unsplash.com/photo-1519046904884-53103b34b206',
      summary:
          'Iconic WA reef-and-point setup with a polished surf-travel feel and year-round credibility.',
    ),
    SpotModel(
      id: 'spot_surfers_point',
      name: 'Surfers Point',
      country: 'Australia',
      region: 'Western Australia',
      area: 'Margaret River',
      latitude: -33.9534,
      longitude: 114.9932,
      difficulty: 'advanced',
      bestMonths: const ['Apr', 'May', 'Jun', 'Jul', 'Aug'],
      waveHeightM: 2.2,
      waterTempC: 20,
      imageUrl: 'https://images.unsplash.com/photo-1473116763249-2faaef81ccda',
      summary:
          'Heavy open-ocean WA stage with serious size, power, and global contest recognition.',
    ),
    SpotModel(
      id: 'spot_snapper',
      name: 'Snapper Rocks',
      country: 'Australia',
      region: 'Queensland',
      area: 'Gold Coast',
      latitude: -28.1649,
      longitude: 153.5482,
      difficulty: 'advanced',
      bestMonths: const ['Feb', 'Mar', 'Apr', 'May', 'Jun'],
      waveHeightM: 1.7,
      waterTempC: 24,
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
      summary:
          'World-famous superbank right with long walls and serious travel-destination gravity.',
    ),
    SpotModel(
      id: 'spot_burleigh',
      name: 'Burleigh Heads',
      country: 'Australia',
      region: 'Queensland',
      area: 'Gold Coast',
      latitude: -28.0918,
      longitude: 153.4544,
      difficulty: 'intermediate',
      bestMonths: const ['Mar', 'Apr', 'May', 'Jun'],
      waveHeightM: 1.5,
      waterTempC: 24,
      imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
      summary:
          'Crowded but beautiful point setup with one of the best hill-and-lineup views in Australia.',
    ),
    SpotModel(
      id: 'spot_noosa',
      name: 'First Point',
      country: 'Australia',
      region: 'Queensland',
      area: 'Noosa',
      latitude: -26.3847,
      longitude: 153.0907,
      difficulty: 'beginner',
      bestMonths: const ['Mar', 'Apr', 'May', 'Jun'],
      waveHeightM: 1.2,
      waterTempC: 24,
      imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
      summary:
          'Classic longboard-friendly point with smooth walls and huge surf-culture appeal.',
    ),
    SpotModel(
      id: 'spot_bells',
      name: 'Bells Beach',
      country: 'Australia',
      region: 'Victoria',
      area: 'Torquay',
      latitude: -38.3712,
      longitude: 144.283,
      difficulty: 'advanced',
      bestMonths: const ['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
      waveHeightM: 1.9,
      waterTempC: 17,
      imageUrl: 'https://images.unsplash.com/photo-1519046904884-53103b34b206',
      summary:
          'Cold-water icon with long walls, big surf heritage, and a serious performance identity.',
    ),
    SpotModel(
      id: 'spot_bondi',
      name: 'Bondi',
      country: 'Australia',
      region: 'New South Wales',
      area: 'Sydney',
      latitude: -33.8915,
      longitude: 151.2767,
      difficulty: 'beginner',
      bestMonths: const ['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
      waveHeightM: 1.0,
      waterTempC: 21,
      imageUrl: 'https://images.unsplash.com/photo-1493558103817-58b2924bce98',
      summary:
          'Famous Sydney beach with accessible peaks, heavy crowds, and huge content potential.',
    ),
    SpotModel(
      id: 'spot_manly',
      name: 'Manly',
      country: 'Australia',
      region: 'New South Wales',
      area: 'Sydney',
      latitude: -33.7969,
      longitude: 151.287,
      difficulty: 'intermediate',
      bestMonths: const ['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
      waveHeightM: 1.2,
      waterTempC: 21,
      imageUrl: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21',
      summary:
          'Sydney staple with multiple peaks, surf history, and easy urban surf-travel storytelling.',
    ),
    SpotModel(
      id: 'spot_byron',
      name: 'The Pass',
      country: 'Australia',
      region: 'New South Wales',
      area: 'Byron Bay',
      latitude: -28.6326,
      longitude: 153.636,
      difficulty: 'beginner',
      bestMonths: const ['Mar', 'Apr', 'May', 'Jun', 'Jul'],
      waveHeightM: 1.3,
      waterTempC: 23,
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
      summary:
          'Long cruisy right with a huge learner and longboard following in one of Australia’s most famous towns.',
    ),
  ];

  static final forecasts = [
    for (final spot in spots) ..._estimatedForecastsForSpot(spot),
  ];

  static final trips = [
    TripModel(
      id: 'trip_1',
      title: 'Dry Season Surf Sprint',
      destination: 'Bali',
      startDate: '2026-05-10',
      endDate: '2026-05-18',
      travelers: 2,
      notes: 'Stay near Uluwatu and rent scooters.',
      budgetUsd: 1800,
    ),
  ];

  static final alerts = [
    AlertModel(
      id: 'alert_1',
      spotId: 'spot_uluwatu_peak',
      minWaveHeightM: 1.5,
      maxWindKts: 14,
      enabled: true,
      nextCheckAt: '2026-04-09T03:00:00Z',
    ),
  ];

  static final friends = [
    FriendProfileModel(
      id: 'friend_lina',
      displayName: 'Lina Reef',
      homeRegion: 'Canggu',
      avatarEmoji: 'L',
      vibe: 'Longboard mornings, coffee after.',
    ),
    FriendProfileModel(
      id: 'friend_ari',
      displayName: 'Ari Dawn',
      homeRegion: 'Uluwatu',
      avatarEmoji: 'A',
      vibe: 'Intermediate, early sessions, shares rides.',
    ),
    FriendProfileModel(
      id: 'friend_jo',
      displayName: 'Jo Tide',
      homeRegion: 'Siargao',
      avatarEmoji: 'J',
      vibe: 'Looking for reef buddies and cheap eats.',
    ),
  ];

  static final posts = [
    SocialPostModel(
      id: 'post_uluwatu_dawn',
      userId: 'usr_demo',
      authorName: 'Maya Surfer',
      spotId: 'spot_uluwatu_peak',
      postType: 'general',
      visibility: 'public',
      body:
          'Thinking dawn patrol at Uluwatu tomorrow if the wind stays light. Anyone keen?',
      media: const [],
      meetupDate: '2026-04-22',
      createdAt: '2026-04-21T04:00:00Z',
    ),
    SocialPostModel(
      id: 'post_balangan_friends',
      userId: 'friend_ari',
      authorName: 'Ari Dawn',
      spotId: 'spot_balangan',
      postType: 'general',
      visibility: 'friends',
      body:
          'Looking for someone to split a scooter ride to Balangan this week.',
      media: const [],
      meetupDate: '2026-04-24',
      createdAt: '2026-04-20T22:00:00Z',
    ),
  ];

  static final plans = [
    BillingPlanModel(
      id: 'free',
      name: 'Free',
      priceUsdMonthly: 0,
      features: const ['Spot explorer', '3 alerts', 'Ad-supported feed'],
    ),
    BillingPlanModel(
      id: 'premium',
      name: 'Premium',
      priceUsdMonthly: 7.99,
      features: const [
        'Unlimited alerts',
        'Trip planner',
        'Ad-light home feed',
      ],
    ),
  ];

  static final ads = [
    AdModel(
      id: 'ad_1',
      title: 'Boardbag sale for island hoppers',
      partner: 'Saltline Gear',
      cta: 'Shop now',
      imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438',
      placement: 'home_feed',
    ),
  ];

  static final dashboard = DashboardModel(
    featuredSpot: spots.first,
    topForecast: forecasts.first,
    upcomingTrip: trips.first,
    alertsEnabled: 1,
  );

  static List<ForecastModel> _estimatedForecastsForSpot(SpotModel spot) {
    final (waveMin, waveMax) = _waveBandForDifficulty(spot.difficulty);
    final (windMin, windMax) = _windBandForDifficulty(spot.difficulty);
    final quality = spot.difficulty == 'beginner' ? 'fair' : 'good';

    return List<ForecastModel>.generate(
      5,
      (index) => ForecastModel(
        id: 'est_${spot.id}_${index + 1}',
        spotId: spot.id,
        day: '2026-04-${(15 + index).toString().padLeft(2, '0')}',
        waveHeightM: null,
        waveHeightMinM: waveMin,
        waveHeightMaxM: waveMax,
        periodS: null,
        windKts: null,
        windKtsMin: windMin,
        windKtsMax: windMax,
        quality: quality,
        swellWaveHeightM: null,
        windWaveHeightM: null,
        seaSurfaceTemperatureC: null,
        source: 'estimated',
        confidence: 'estimated',
        confidenceNote:
            'Estimated surf band based on the spot profile while live marine data is unavailable.',
      ),
    );
  }

  static (double, double) _waveBandForDifficulty(String difficulty) {
    switch (difficulty) {
      case 'beginner':
        return (0.3, 0.8);
      case 'advanced':
        return (1.6, 2.8);
      default:
        return (0.8, 1.6);
    }
  }

  static (double, double) _windBandForDifficulty(String difficulty) {
    switch (difficulty) {
      case 'beginner':
        return (6.0, 14.0);
      case 'advanced':
        return (10.0, 22.0);
      default:
        return (8.0, 18.0);
    }
  }
}
